version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: secret
      MINIO_ROOT_PASSWORD: secret123#M1920
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data: